ARG BASE_IMAGE=golang:1.10-alpine
FROM ${BASE_IMAGE}

COPY _deployman /opt/deployman/_deployman
COPY Makefile /opt/deployman/Makefile
COPY .common.mk /opt/deployman/.common.mk

WORKDIR /opt/deployman

RUN apk add --no-cache make bash
RUN make tools

ENTRYPOINT ["make"]
CMD ["build"]
