---
sudo: required
services:
  - docker

language: go

go:
  - "1.10"

git:
  depth: false

before_install:
  - env | sort
  - git --no-pager log --graph --decorate --oneline -25

install:
  - sudo apt-get install httpie
  - make tools

before_script:
  - export APP_NAME=`basename ${PWD}`
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"

script:
  - make lint
  - make build
  - make test

after_success:
  - make ci
